"use client"
import { useRouter } from 'next/navigation';
import { useEffect } from 'react';
// import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./element/Header";
import Footer from "./element/Footer";
import { isAuthenticated } from '../util/auth';


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();

  useEffect(() => {
    if (!isAuthenticated()) {
      router.push('/login'); 
    }
  }, [router]);
  return (
    <html lang="en">


      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
